version: '1.0'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: django_web
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django_postgres_db
    ports:
      - "5432:5432"

  django_app:
    build: .
    volumes:
      - .:/app
    environment:
      DB_USER: django_web
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_NAME: django_postgres_db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres