# Generated by Django 4.2.4 on 2023-08-30 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visit_counter", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="count",
            new_name="number_of_visits",
        ),
    ]
