name: Django Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-image:
    runs-on: ubuntu-latest
    container: python:3.8-slim
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Verify formating
      run: black . --check
    - name: Verify linting
      run: ruff check .
    - name: Tests
      run: coverage run manage.py test
    - name: Quality Gate
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Check Quality Gate
      id: sonar-check-quality-gate
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  push_image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - uses: actions/checkout@v3
    - name: Dockerize
      run: |
        docker login -u=${{secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{secrets.DOCKER_REGISTRY }}:latest
        docker push ${{secrets.DOCKER_REGISTRYs }}:latest
